/*===========================================================================
     Added to RK base RMIS product as 01/21/2014
    ===========================================================================*/
    
@isTest
public class ReedDisabilityDurationRequestInfo_Test{
    public static testmethod void testReedDisabilityDurationRequestInfo() {
        ReedDisabilityDurationRequestInfo testReedDisabilityDurationRequestInfo = new ReedDisabilityDurationRequestInfo('testICD9', 'testJobClass');
    }
}